# Generated by Django 6.0.4 on 2026-09-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_martycoinwallet_martycointransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='martycointransaction',
            name='reference_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
