# Generated by Django 6.0.4 on 2026-09-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_martycointransaction_reference_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
