# Generated by Django 6.0.4 on 2026-09-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_address_phone_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='phone_verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
