# Generated by Django 6.0.4 on 2026-09-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hamper_item',
            field=models.BooleanField(default=False),
        ),
    ]
