# Generated by Django 6.1.1 on 2026-09-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_hamper_item',
            field=models.BooleanField(default=True),
        ),
    ]
